//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_match.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bireysel_uyelik
    {
        public int id { get; set; }
        public string b_adi { get; set; }
        public string b_soyadi { get; set; }
        public string b_tc { get; set; }
        public string b_email { get; set; }
        public string b_telNo { get; set; }
        public string b_adres { get; set; }
        public Nullable<System.DateTime> b_dogumTarihi { get; set; }
        public string b_sifre { get; set; }
        public string b_foto { get; set; }
        public Nullable<int> egitimDurum_id { get; set; }
        public string b_okul { get; set; }
        public string b_tecrube { get; set; }
        public Nullable<int> cinsiyet_id { get; set; }
        public string b_ehliyet { get; set; }
        public string b_cv { get; set; }
        public Nullable<int> b_bireyselmi { get; set; }
        public Nullable<System.DateTime> b_uyelikTarihi { get; set; }
        public string dil_adi { get; set; }
        public string di_seviye { get; set; }
    
        public virtual cinsiyet cinsiyet { get; set; }
        public virtual egitim_durum egitim_durum { get; set; }
    }
}
