//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_match.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class is_ilan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public is_ilan()
        {
            this.yorumlar = new HashSet<yorumlar>();
        }
    
        public int id { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> kurumsal_id { get; set; }
        public string ilan_ad { get; set; }
        public string is_tanim { get; set; }
        public Nullable<int> is_maas { get; set; }
        public Nullable<int> is_sayi { get; set; }
        public Nullable<int> sehir_id { get; set; }
        public Nullable<System.DateTime> ilan_baslangic { get; set; }
        public Nullable<System.DateTime> ilan_bitis { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual kurumsal_uyelik kurumsal_uyelik { get; set; }
        public virtual sehirler sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorumlar> yorumlar { get; set; }
    }
}
