//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_match.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kurumsal_uyelik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kurumsal_uyelik()
        {
            this.is_ilan = new HashSet<is_ilan>();
        }
    
        public int id { get; set; }
        public string k_ilanVerenAdi { get; set; }
        public string k_sirketAdi { get; set; }
        public Nullable<int> pozisyon_id { get; set; }
        public string k_sifre { get; set; }
        public string k_foto { get; set; }
        public string k_telNo { get; set; }
        public Nullable<System.DateTime> k_kurulusDate { get; set; }
        public string k_email { get; set; }
        public string k_hakkinda { get; set; }
        public string k_merNo { get; set; }
        public Nullable<int> b_bireyselmi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<is_ilan> is_ilan { get; set; }
        public virtual y_pozisyon y_pozisyon { get; set; }
    }
}
