//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_match.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsMatchEntities : DbContext
    {
        public IsMatchEntities()
            : base("name=IsMatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bireysel_uyelik> bireysel_uyelik { get; set; }
        public virtual DbSet<cinsiyet> cinsiyet { get; set; }
        public virtual DbSet<egitim_durum> egitim_durum { get; set; }
        public virtual DbSet<hakkimizda> hakkimizda { get; set; }
        public virtual DbSet<is_ilan> is_ilan { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<kurumsal_uyelik> kurumsal_uyelik { get; set; }
        public virtual DbSet<sehirler> sehirler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<y_pozisyon> y_pozisyon { get; set; }
        public virtual DbSet<yonetici> yonetici { get; set; }
        public virtual DbSet<yorumlar> yorumlar { get; set; }
    }
}
