//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_match.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class y_pozisyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public y_pozisyon()
        {
            this.kurumsal_uyelik = new HashSet<kurumsal_uyelik>();
            this.yonetici = new HashSet<yonetici>();
        }
    
        public int id { get; set; }
        public string pozisyon_adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kurumsal_uyelik> kurumsal_uyelik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yonetici> yonetici { get; set; }
    }
}
