//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_match.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yonetici
    {
        public int id { get; set; }
        public string y_adi { get; set; }
        public string y_soyadi { get; set; }
        public Nullable<int> pozisyon_id { get; set; }
        public string y_foto { get; set; }
        public string y_mail { get; set; }
    
        public virtual y_pozisyon y_pozisyon { get; set; }
    }
}
